// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: visitor.proto

package visitorpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AddVisitorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Unixnano             int64    `protobuf:"varint,2,opt,name=unixnano,proto3" json:"unixnano,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVisitorRequest) Reset()         { *m = AddVisitorRequest{} }
func (m *AddVisitorRequest) String() string { return proto.CompactTextString(m) }
func (*AddVisitorRequest) ProtoMessage()    {}
func (*AddVisitorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_visitor_bb4d44ebd14d5876, []int{0}
}
func (m *AddVisitorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVisitorRequest.Unmarshal(m, b)
}
func (m *AddVisitorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVisitorRequest.Marshal(b, m, deterministic)
}
func (dst *AddVisitorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVisitorRequest.Merge(dst, src)
}
func (m *AddVisitorRequest) XXX_Size() int {
	return xxx_messageInfo_AddVisitorRequest.Size(m)
}
func (m *AddVisitorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVisitorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddVisitorRequest proto.InternalMessageInfo

func (m *AddVisitorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddVisitorRequest) GetUnixnano() int64 {
	if m != nil {
		return m.Unixnano
	}
	return 0
}

type AddVisitorReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVisitorReply) Reset()         { *m = AddVisitorReply{} }
func (m *AddVisitorReply) String() string { return proto.CompactTextString(m) }
func (*AddVisitorReply) ProtoMessage()    {}
func (*AddVisitorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_visitor_bb4d44ebd14d5876, []int{1}
}
func (m *AddVisitorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVisitorReply.Unmarshal(m, b)
}
func (m *AddVisitorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVisitorReply.Marshal(b, m, deterministic)
}
func (dst *AddVisitorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVisitorReply.Merge(dst, src)
}
func (m *AddVisitorReply) XXX_Size() int {
	return xxx_messageInfo_AddVisitorReply.Size(m)
}
func (m *AddVisitorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVisitorReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddVisitorReply proto.InternalMessageInfo

func (m *AddVisitorReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*AddVisitorRequest)(nil), "visitorpb.AddVisitorRequest")
	proto.RegisterType((*AddVisitorReply)(nil), "visitorpb.AddVisitorReply")
}
func NewPopulatedAddVisitorRequest(r randyVisitor, easy bool) *AddVisitorRequest {
	this := &AddVisitorRequest{}
	this.Id = string(randStringVisitor(r))
	this.Unixnano = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Unixnano *= -1
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedVisitor(r, 3)
	}
	return this
}

func NewPopulatedAddVisitorReply(r randyVisitor, easy bool) *AddVisitorReply {
	this := &AddVisitorReply{}
	this.Ok = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedVisitor(r, 2)
	}
	return this
}

type randyVisitor interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneVisitor(r randyVisitor) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringVisitor(r randyVisitor) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneVisitor(r)
	}
	return string(tmps)
}
func randUnrecognizedVisitor(r randyVisitor, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldVisitor(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldVisitor(dAtA []byte, r randyVisitor, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateVisitor(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateVisitor(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateVisitor(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateVisitor(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateVisitor(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateVisitor(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateVisitor(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}

func init() { proto.RegisterFile("visitor.proto", fileDescriptor_visitor_bb4d44ebd14d5876) }

var fileDescriptor_visitor_bb4d44ebd14d5876 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xcb, 0x2c, 0xce,
	0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x72, 0x0b, 0x92, 0xa4,
	0x74, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xd3, 0xf3, 0xd3, 0xf3,
	0xf5, 0xc1, 0x2a, 0x92, 0x4a, 0xd3, 0xc0, 0x3c, 0x30, 0x07, 0xcc, 0x82, 0xe8, 0x54, 0xb2, 0xe7,
	0x12, 0x74, 0x4c, 0x49, 0x09, 0x83, 0x68, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2,
	0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x92,
	0xe2, 0xe2, 0x28, 0xcd, 0xcb, 0xac, 0xc8, 0x4b, 0xcc, 0xcb, 0x97, 0x60, 0x52, 0x60, 0xd4, 0x60,
	0x0e, 0x82, 0xf3, 0x95, 0x14, 0xb9, 0xf8, 0x91, 0x0d, 0x28, 0xc8, 0xa9, 0x04, 0x69, 0xcf, 0xcf,
	0x06, 0x6b, 0xe7, 0x08, 0x62, 0xca, 0xcf, 0x76, 0xe2, 0xff, 0xf1, 0x50, 0x8e, 0x31, 0x0a, 0xe1,
	0xc6, 0x24, 0x36, 0xb0, 0xdd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xc2, 0x7a, 0x91,
	0xc6, 0x00, 0x00, 0x00,
}
